version: '3.1'
services:
  ironsight-db:
    image: mariadb:latest
    container_name: ironsight-db
    cap_add:
      - SYS_NICE
    # Open SQL server to host for debugging
    # ports: 
    #   - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
    volumes:
      - ironsight-db-data:/var/lib/mysql
      - ./ironsight-sql-db/ironsight_db.sql:/docker-entrypoint-initdb.d/dump.sql
  ironsight-dashboard:
    build:
      context: ./ironsight
      dockerfile: ./Dockerfile
    container_name: ironsight-dashboard
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      REACT_APP_IRONSIGHT_API_URL: ${IRONSIGHT_API_URL}
      REACT_APP_HARVESTER_URL: ${HARVESTER_URL}
  ironsight-api:
    build:
      context: ./ironsight-api-handler
      dockerfile: ./Dockerfile
    container_name: ironsight-api
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      HARVESTER_URL: ${HARVESTER_URL}
      HARVESTER_API_TOKEN: ${HARVESTER_API_TOKEN}
      ELASTIC_FLEET_URL: ${ELASTIC_FLEET_URL}
      ELASTIC_FLEET_API_TOKEN: ${ELASTIC_FLEET_API_TOKEN}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      ELASTICSEARCH_API_TOKEN: ${ELASTICSEARCH_API_TOKEN}
      ELASTIC_VERSION: ${ELASTIC_VERSION}

volumes:
  ironsight-db-data:
    driver: local
    name: ironsight-db-data