version: '3.1'
services:
  ironsight-db:
    image: mariadb:latest
    container_name: ironsight-db
    cap_add:
      - SYS_NICE
    ports: 
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: ironsight
      MYSQL_USER: ironsight
      MYSQL_PASSWORD: ironsight
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - ironsight-db-data:/var/lib/mysql
      - ./ironsight-sql-db/ironsight_db.sql:/docker-entrypoint-initdb.d/dump.sql
  ironsight-dashboard:
    build:
      context: ./ironsight
      dockerfile: ./Dockerfile
    container_name: ironsight-dashboard
    restart: unless-stopped
    ports:
      - 3000:3000
  ironsight-api:
    build:
      context: ./ironsight-api-handler
      dockerfile: ./Dockerfile
    container_name: ironsight-api
    restart: unless-stopped
    ports:
      - 80:80

volumes:
  ironsight-db-data:
    driver: local
    name: ironsight-db-data